### ISSUE TITLE
Class "zfhassaan\Payfast\PayfastServiceProvider" not found

### ISSUE THREAD

**Issue by ByronCoet** [zfhassaan/payfast#5]
After installing on laravel 10 - composer require - setting allais and service provider I thnk continually get

Class "zfhassaan\Payfast\PayfastServiceProvider" not found

Any help appreciated

**Comment by ByronCoet** [comment]
solved the issue  -was upper case lower case on paths - looks like the owner uses windows, but linux is strict on the paths..

**Comment by zfhassaan** [comment]
I'll mark this issue to close.
